    - name: Initialize pacman keyring
      become: true
      command: sudo -S pacman-key --init

    - name: Populate pacman keyring (archlinux)
      become: true
      command: sudo -S pacman-key --populate archlinux
    
    - name: Populate pacman keyring (holo)
      become: true
      command: sudo -S pacman-key --populate holo