---
- name: Ensure 'ansible' user exists
  become: true
  user:
    name: ansible
    comment: Ansible automation user
    shell: /bin/bash
    create_home: yes
  register: check_ansible_user

- name: Allow 'ansible' user passwordless sudo
  become: true
  copy:
    dest: /etc/sudoers.d/ansible
    content: "ansible ALL=(ALL) NOPASSWD: ALL\n"
    mode: '0440'
  when: check_ansible_user.changed

- name: Ensure .ssh directory exists
  become: true
  file:
    path: /home/ansible/.ssh
    state: directory
    owner: ansible
    group: ansible
    mode: '0700'
  when: check_ansible_user.changed

- name: Add authorized key for ansible user
  become: true
  authorized_key:
    user: ansible
    state: present
    key: "{{ lookup('file', '/home/pawel/.ssh/ansible_ed25519.pub') }}"
  when: check_ansible_user.changed